---
- name: "Set ip forward on"
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present

- name: Iptables rules
  ansible.builtin.shell: "{{ item }}"
  loop:
    - iptables -t nat -I POSTROUTING -s {{ openvpn_server_network }}/{{ openvpn_server_netmask }} -j MASQUERADE
    - iptables -A INPUT -i lo -j ACCEPT
    - iptables -A OUTPUT -o lo -j ACCEPT
    - iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
    - iptables -A INPUT -p tcp --dport 22 -j ACCEPT
    - iptables -A INPUT -p tcp --dport 53 -j ACCEPT
    - iptables -A INPUT -p udp --dport 1194 -j ACCEPT
    - iptables -A INPUT -p udp --dport 53 -j ACCEPT
    - iptables -A INPUT -p udp --dport 123 -j ACCEPT
    - iptables -P INPUT DROP
    - iptables-save > /etc/iptables/rules.v4
