---
- name: Create openvpn config file
  template:
    src: server.conf.j2
    dest: "{{ openvpn_base_dir }}/{{ openvpn_config_file }}.conf"
    owner: root
    group: root
  notify:
    - restart openvpn

- name: Copy openvpn logrotate config file
  copy:
    src: openvpn_logrotate.conf
    dest: /etc/logrotate.d/openvpn.conf
    owner: root
    group: root
    mode: 0400

- name: Ensure group 'nogroup' is present
  group:
    name: nogroup
    state: present
    system: yes

- name: Setup openvpn auto-start & start
  service:
    name: "{{ openvpn_service_name }}"
    enabled: yes
    state: started
